2018-05-14 20:56:10.801 [error] <0.374.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.379.0> exit with reason normal in context child_terminated
2018-05-14 20:56:10.828 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-14 20:56:10.830 [info] <0.33.0> Application xmerl started on node nonode@nohost
2018-05-14 20:56:10.831 [info] <0.33.0> Application jsx started on node nonode@nohost
2018-05-14 20:56:10.835 [info] <0.33.0> Application ranch started on node nonode@nohost
2018-05-14 20:56:10.836 [info] <0.33.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-05-14 20:56:10.837 [info] <0.33.0> Application recon started on node nonode@nohost
2018-05-14 20:56:10.837 [info] <0.33.0> Application rabbit_common started on node nonode@nohost
2018-05-14 20:56:10.842 [info] <0.33.0> Application amqp_client started on node nonode@nohost
2018-05-14 20:56:10.842 [info] <0.33.0> Application amqp started on node nonode@nohost
2018-05-14 20:56:10.842 [info] <0.33.0> Application rabbitmq_tutorials started on node nonode@nohost
2018-05-14 21:50:46.390 [error] <0.462.0> gen_server <0.462.0> terminated with reason: {socket_error,timeout}
2018-05-14 21:50:46.390 [error] <0.462.0> CRASH REPORT Process <0.462.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-05-14 21:50:46.390 [error] <0.456.0> gen_server <0.456.0> terminated with reason: {socket_error,timeout}
2018-05-14 21:50:46.390 [error] <0.456.0> CRASH REPORT Process <0.456.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-05-14 21:50:46.391 [error] <0.455.0> Supervisor {<0.455.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.11305>, <0.456.0>, <0.460.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:42355 -> 127.0.0.1:5672">>) at <0.462.0> exit with reason {socket_error,timeout} in context child_terminated
2018-05-14 21:50:46.391 [error] <0.455.0> Supervisor {<0.455.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.11305>, <0.456.0>, <0.460.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:42355 -> 127.0.0.1:5672">>) at <0.462.0> exit with reason reached_max_restart_intensity in context shutdown
2018-05-14 21:50:46.391 [error] <0.454.0> Supervisor {<0.454.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.455.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.456.0> exit with reason {socket_error,timeout} in context child_terminated
2018-05-14 21:50:46.391 [error] <0.454.0> Supervisor {<0.454.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.455.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.456.0> exit with reason reached_max_restart_intensity in context shutdown
